scan_timeout = 10
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$container\
$dotnet\
$erlang\
$golang\
$kotlin\
$nodejs\
$python\
$rust\
$nix_shell\
$memory_usage\
$aws\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""
