# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 200
format = """
$directory\

$git_branch\
$git_metrics\
$git_status\
$fill\
$nodejs\
$golang\
$rust\
$c\
$python\
$swift\
$line_break\
$jobs\
$cmd_duration\
$status\
$character
"""

scan_timeout = 10

[battery]
format = "[$symbol$percentage]($style)"
[[battery.display]]
threshold = 100

[username]
format = "[$user@]($style)"
show_always = true
style_user = "bold"

[hostname]
format = "[$hostname]($style) "
ssh_only = false
style = "bold"

[directory]
style = "bold gray"
truncation_length = 3
repo_root_style = "bold italic cyan"

[git_branch]
format = '([$symbol$branch]($style) )'
style = "bold white"

[git_status]
format = '([\($all_status$ahead_behind\)]($style ))'

[git_metrics]
disabled = false
format = '([+$added]($added_style))(/[-$deleted]($deleted_style) )'

[line_break]
disabled = false

[nodejs]
format = " [$symbol($version)]($style)"
style = "bold 35"
symbol = "啡"
version_format = "${raw}"

[swift]
format = " [$symbol($version)]($style)"
symbol = "䨹"
style = "bold 208"
disabled = false

[package]
format = " [$symbol$version]($style) "
style = "bold 009"
symbol = "包"
version_format = "${raw}"

[python]
format = ' [${symbol}(${version}) (\($virtualenv\))]($style)'
pyenv_prefix = "pyenv "
pyenv_version_name = true
style = "bold 221"
symbol = '蟒'
version_format = "${raw}"

[golang]
format = " [$symbol($version)]($style)"
symbol = "鼴"
version_format = "${raw}"

[rust]
format = " [$symbol($version)]($style)"
symbol = "銹"

[c]
format = " [$symbol($version)]($style)"
commands = [['clang', '--version']]

[cmd_duration]
format = "[$duration]($style) "
min_time = 30_000

[status]
disabled = false
format = '[$symbol $status]($style) '
not_executable_symbol = "尀"
not_found_symbol = "𠳕"
sigint_symbol = "断"
signal_symbol = "烽"
symbol = "✗"

[character]
error_symbol = "[❯](bold red) "
format = "$symbol"
success_symbol = "[❯](bold) "

[time]
format = "[$time]($style)"
use_12hr = true
time_format = "%l:%M %p"
style = "bold gray"
disabled = false

[fill]
symbol = " "
