add_newline = false
command_timeout = 200
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_metrics\
$git_status\
$package\
$golang\
$kotlin\
$python\
$custom\
$time\
$line_break\
$jobs\
$cmd_duration\
$status\
$character"""
scan_timeout = 10

[username]
format = "[$user@]($style)"
show_always = true
style_user = "bold"

[hostname]
format = "[$hostname]($style) "
ssh_only = false
style = "bold"

[directory]
style = "bold cyan"

[git_branch]
format = '([\[]()[ $symbol$branch]($style) )'
style = "bold white"

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )[\]]() '

[git_metrics]
disabled = false
format = '([+$added]($added_style))(/[-$deleted]($deleted_style) )'

[line_break]
disabled = false

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold 35"
symbol = "啡"
version_format = "${raw}"

[package]
format = "[$symbol$version]($style) "
style = "bold 009"
symbol = "包"
version_format = "${raw}"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_prefix = "pyenv "
pyenv_version_name = true
style = "bold 221"
symbol = '蟒'
version_format = "${raw}"

[golang]
format = "[$symbol($version )]($style)"
symbol = "鼴"
version_format = "${raw}"

[cmd_duration]
format = "[$duration]($style) "
min_time = 30_000

[status]
disabled = false
format = '[$symbol $status]($style) '
not_executable_symbol = "尀"
not_found_symbol = "𠳕"
sigint_symbol = "断"
signal_symbol = "烽"
symbol = "✗"

[character]
error_symbol = "[❯](bold red) "
format = "$symbol"
success_symbol = "[❯](bold) "
